### ISSUE TITLE
Documentation: Typical tasks

### ISSUE THREAD

**Issue by markusbaumeister** [gap-packages/SimplicialSurfaces#111]
Write a documentation chapter "Typical tasks", which contains several "normal" tasks and shows how these tasks are solved with the methods of the package. These should be tasks that are of general importance and should be understandable/interesting for non-experts.

Example sections:
-> creating surfaces
-> drawing surfaces
-> modify surfaces
-> subdivide surfaces
-> analyse surfaces

**Comment by MeikeWeiss** [comment]
The idea was to write a separate tutorial, as you can see in PR#239. But it does not make sense to do this in this git repository. Thus, we close this Issue and the pull request.
