### ISSUE TITLE
Rename the repository?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/SimplicialSurfaces#200]
Since the GAP package is named `SimplicialSurfaces` ideally the repository should have the same name. This can be done via the repository settings. I can do this for you, too, if you prefer.

**Comment by aniemeyer** [comment]
It would be very much appreciated if you could do that.

**Comment by fingolfin** [comment]
Done. Next various URLs in the README, PackageInfo.g and other files should be adapted to the change
