### ISSUE TITLE
UmbrellaTipDescriptor

### ISSUE THREAD

**Issue by aniemeyer** [gap-packages/SimplicialSurfaces#255]
The umbrella tip descriptor assumes that the vertices are consecutive. This can have the consequence that
UmbrellaTipDescriptor(surf)[i] is not the Umbreall tip of the vertex UmbrellaDescriptor(surf)[i].

 u := [,(3,5,7), [3,5],[5,7],[3,7] ];     
[ , (3,5,7), [ 3, 5 ], [ 5, 7 ], [ 3, 7 ] ]
gap> surf := SimplicialSurfaceByUmbrellaDescriptor(u);
simplicial surface (4 vertices, 6 edges, and 3 faces)
gap> Vertices(surf);
[ 2, 3, 4, 5 ]
gap> UmbrellaTipDescriptorOfSurface(surf);
[ (3,5,4), [ 5, 2, 4 ], [ 3, 2, 5 ], [ 3, 2, 4 ] ]
gap> UmbrellaDescriptorOfSurface(surf);
[ , (3,7,5), [ 3, 5 ], [ 5, 7 ], [ 3, 7 ] ]

**Comment by FlynnFehre** [comment]
I fixed this and created a pull request regarding the issue.
