### ISSUE TITLE
Implement Star und Link

### ISSUE THREAD

**Issue by markusbaumeister** [gap-packages/SimplicialSurfaces#62]
In the study of simplicial complexes the concepts of star and link are often used.

They should be implemented in a proper way (i.e. designed and documented).

**Comment by MeikeWeiss** [comment]
What is meant by link? And in which chapter should that be written?

**Comment by markusbaumeister** [comment]
https://en.wikipedia.org/wiki/Simplicial_complex#Closure,_star,_and_link

The best current chapter might be "Navigating the incidence structure" (as the final section), since that chapter already contains several local methods.

**Comment by TomGoertzen** [comment]
For star one could use SubcomplexByFaces and Umbrella; For Link one could use Umbrella Path
